branch-defaults:
  default:
    environment: udagram-c3-restapi-jinrong-dev-dev
    group_suffix: null
deploy:
  artifact: ./www/Archive.zip
global:
  application_name: udagram-c3-restapi-jinrong-dev
  branch: null
  default_ec2_keyname: stonexjr-aws-private-key
  default_platform: Node.js
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
