# https://kubernetes.io/docs/concepts/configuration/secret/#creating-a-secret-manually
apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
type: Opaque
data:
  credentials: ___INSERT_AWS_CREDENTIALS_FILE__BASE64____