apiVersion: v1
kind: Pod
metadata:
  name: pod-backend-user
spec:
  containers:
  - image: stonexjr/udacity-restapi-user
    name: backend-user
    imagePullPolicy: Always          
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "1024Mi"
        cpu: "500m"       
    ports:
    - containerPort: 8100
  restartPolicy: Always