apiVersion: v1
kind: Pod
metadata:
  name: pod-backend-user
spec:
  containers:
  - image: stonexjr/udacity-restapi-user
    name: backend-user
    imagePullPolicy: Always          
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "1024Mi"
        cpu: "500m"       
    ports:
    - containerPort: 8080
    env:
      - name: POSTGRESS_USERNAME
        value: ${POSTGRESS_USERNAME}
      - name: POSTGRESS_PASSWORD
        value: ${POSTGRESS_PASSWORD}
      - name: POSTGRESS_DB
        value: ${POSTGRESS_DB}
      - name: POSTGRESS_HOST
        value: ${POSTGRESS_HOST}
      - name: AWS_REGION
        value: ${AWS_REGION}
      - name: AWS_PROFILE
        value: "DEPLOY"
      - name: AWS_BUCKET
        value: ${AWS_BUCKET}
  restartPolicy: Always