version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: stonexjr/reverseproxy
  backend_user:
    build:
      context: ../../udacity-c3-restapi-user
    image: stonexjr/udacity-restapi-user
  backend_feed:
    build:
      context: ../../udacity-c3-restapi-feed  
    image: stonexjr/udacity-restapi-feed
  frontend:
    build:
      context: ../../udacity-c3-frontend
    image: stonexjr/udacity-frontend:local
